language: generic
os: linux
dist: focal
arch: arm64-graviton2 # in AWS over Graviton2 CPU
virt: lxd             # required, routes to an LXD container
install: bash scripts/install-dependencies.sh
before_script: bash scripts/start-services.sh
before_install: bash scripts/before-install.sh
addons:
  firefox: latest
deploy:
  - provider: cloudfoundry
    edge: true
    skip_cleanup: true
    username: joel.stobart@wearesnook.com
    password: S220tEq9893Uw44Igsq
    api: https://api.london.cloud.service.gov.uk
    organization: mhclg-local-digital
    space: sandbox
    on:
      branch: main
branches:
  only:
    - main