language: generic
os: linux
dist: focal
arch: arm64-graviton2 # in AWS over Graviton2 CPU
virt: lxd             # required, routes to an LXD container
deploy:
  - provider: cloudfoundry
    edge: true
    skip_cleanup: true
    username: joel.stobart@wearesnook.com
    password: S220tEq9893Uw44Igsq
    api: https://api.london.cloud.service.gov.uk
    organization: mhclg-local-digital
    space: sandbox
    on:
      branch: main
  - provider: cloudfoundry
    edge: true
    skip_cleanup: true
    username: joel.stobart@wearesnook.com
    password: S220tEq9893Uw44Igsq
    api: https://api.london.cloud.service.gov.uk
    organization: mhclg-local-digital
    space: staging
    on:
      branch: staging
branches:
  only:
    - main
    - staging